name: cyberpunkkillerapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  cached_network_image: ^2.2.0+1
  tinycolor: ^1.0.2
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+2
  path_provider: ^1.6.11
#  painter: ^0.4.0
  flutter_signature_view: ^1.1.1
  wallpaper_manager: ^1.0.7
  overlay_support: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/



  fonts:
    - family: Cyberpunk
      fonts:
        - asset: assets/fonts/Cyberpunk-Regular.ttf

